#!/bin/bash
#-----------------------------------------------------------------------
# name : starteasy
# description : Load an Alias AdminSys Toolkit
# author : Luc Soulerin  
# install : wget https://raw.githubusercontent.com/Lux00l/easylazybash/refs/heads/main/starteasy |sh
# usage : ./starteasy
#______________________________________________________________________

set -euo pipefail
if [ "$(id -u)" -eq 0 ]; then
  sudo() { "$@"; }
fi

clear
echo " *****  ****   **** *   *  *    ****  ***** *   *  ****  ****   **** *   * "
echo " *          * *     *   *  *        *    *  *   *  *   *     * *     *   * "
echo " ***    *** *  ***   * *   *     ****   *    * *   ****   ****  ***  ***** "
echo " *     *    *     *   *    *    *   *  *      *    *   * *   *     * *   * "
echo " *****  ***** ****    *    **** ***** *****   *    ****  ***** ****  *   * "

echo Easy Lasy Bash is an Alias ToolKitSet For Linux System Administrator v.1.1.2 lxl

echo updating Aliasses form https://luxool.dev/easylazybash/.bash_aliasses
rm -f ~/.bash_aliasses
wget https://luxool.dev/easylazybash/.bash_aliasses

cat  ~/.bash_aliasses
source ~/.bash_aliasses  >/dev/null 2>&1
